### PR TITLE
Resolved: DB credentials exposed

### PR DESCRIPTION
**Pull request by Gobinath-B**
### Description
.  Resolved: DB credentials exposed by implement .env and .example.env file
.  Implement example env to know the env parameters.
.  dotenv config using npm dotenv
.  nodemon for dev environment

### CODE REVIEW

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-10-04 at 12 31 04

Hey, I guess you got confused between the folders. 
You need not to install any dependencies globally. Its simple. In VS Code terminal, simply change the directory using `cd` command. Check below: 
``
cd server
``
Create `.env` file in server folder & then place those values. 

So, delete the **node_modules** from global folder.

**Comment by Vidip-Ghosh** [comment]
@Gobinath-B if you are facing any issue, kindly ping me in Discord.

**Comment by Gobinath-B** [comment]
@Vidip-Ghosh I moved .example.env to server directory and delete the node_modules and package.json in root directory. You can review and merge it.

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh I moved .example.env to server directory and delete the node_modules and package.json in root directory. You can review and merge it.

Great Work

**Pull request merged**
